cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('delete/<int:product_id>/', views.full_remove, name='full_remove'),
    path('', views.cart_detail, name='cart_detail'),
]

search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'

urlpatterns = [
    path('', views.searchResult, name='searchResult'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
]

shoppingcart/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from shop.models import Product

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

search_app/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    
    def get_url(self):
        return reverse('shop:ProdCatDetail', args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id = _cart_id(request))
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_item=None):
    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items = cart_items, total = total, counter = counter))

def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id = product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id = product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail') 

search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def searchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query':query, 'products':products})

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage

def index(request):
    text_var = 'This is my first django app webpage.'
    return HttpResponse(text_var)

#category view
def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    
    '''Paginator'''
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1

    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
        
    return render(request, 'shop/category.html', {'category':c_page, 'products': products})

def ProdCatDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'shop/product.html', {'product':product})

cart/templates/cart.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block metadescription %}
    This is the shopping cart page. Proceed to review your items and place the order.
{% endblock %}
{% block title %}
    Cart - Perfect Cushion Store 
{% endblock %}

{% block content %}
    {% if not cart_items %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my-title">
                Your shopping cart is empty.
            </h1>
            <br>
            <p class="text-center">
                Please click <a href="{% url 'shop:allProdCat' %}">here</a> to continue shopping.
            </p>
        </div>
    </div>
    {% else %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my-title">
                Your shopping cart
            </h1>
            <br>
        </div>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my-custom-table">
                <thead class="my-custom-thead">
                    <tr>
                        <th colspan="5">
                            Your items
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <a href="{{ cart_item.product.get_absolute_url }}"><img class="float-left rounder custom-image" src="{{ cart_item.product.image.url }}" alt=""></a>
                        </td>
                        <td class="text-left">
                            {{ cart_item.product.name }}
                            <br>
                            SKU: {{ cart_item.product.id }}
                            <br>
                            Unit Price: {{ cart_item.product.price }}
                            <br>
                            Quantity: {{ cart_item.quantity }} x {{ cart_item.product.price }}
                        </td>
                        <td>
                            {{ cart_item.sub_total }}
                        </td>
                        {% if cart_item.quantity < cart_item.product.stock %}
                            <td>
                                <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom-a"><i class="fas fa-plus-circle custom-icon"></i></a>&nbsp;
                                <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom-a"><i class="fas fa-minus-circle custom-icon"></i></a>&nbsp;
                                <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom-a"><i class="fas fa-trash-alt cistom-icon"></i></a>
                            </td>
                            {% else %}
                            <td>
                                <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom-a"><i class="fas fa-minus-circle custom-icon"></i></a>&nbsp;
                                <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom-a"><i class="fas fa-trash-alt cistom-icon"></i></a>
                            </td>
                            <td></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my-custom-table">
                <thead class="my-custom-thead">
                    <tr>
                        <td>
                            Checkout
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Please review your shopping cart items before proceeding with the order payment.
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left">
                            Your total is: <strong>{{ total }}</strong>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my-custom-button">Continue Shopping</a>
            </div>
        </div>
    </div>
    <br>
    {% endif %}
{% endblock %}

search_app/templates/search.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block metadescription %}
    We have a variety of stunning and comfy cushion. Look for the one that suits your needs.
{% endblock %}
{% block title %}
    Search - Perfect Cushion Store 
{% endblock %}

{% block content %}

<div>
    <p class="text-center my-search-text">You have searched for: <b>{{ query }}</b></p>
</div>
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my-bottom-margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
            <div class="card text-center" style="min-width: 18rem;">
                <a href="{{ product.get_url }}"><img class="card-img-top my-image" src="{{ product.image.url }}" alt="{{ product.name }}"></a>
                <div class="card-body">
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.price }}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my-search-text">0 results found.</p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

shop/templates/base.html
{% load staticfiles %}
<!DOCTYPE <!DOCTYPE html>
<html>

<head>
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <meta name="description" content="{% block metadescription %}{% endblock %}">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <title>{% block title %}{% endblock %}</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">

   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

   <!-- CSS -->
   <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/custom.css' %}" />

   <!-- Font -->
   <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
   <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.min.css' %}">

   <!-- <script src="main.js"></script> -->
</head>

<body>
   <div class="container">
      {% include 'header.html' %}
      {% include 'navbar.html' %}
      {% block content %}

      {% endblock %}
   </div>
   {% include 'footer.html' %}

   <!-- JS -->
   <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
   <script src="{% static 'js/popper.min.js' %}"></script>
   <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

shop/templates/footer.html
<div class="footer navbar-fixed-bottom my-footer">
    <p class="text-center">&copy; Udemy Training. All Rights Resevered</p>
</div>

shop/templates/header.html
{% load staticfiles %}
<header>
    <center>
        <a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo.png' %}"></a>
    </center>
</header>

shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            Shop
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a>
            {% for cat in links %}
            <a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a>
            {% endfor %}
          </div>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{ item_count }})</a>
        </li>
        {% endif %}
      </ul>
      <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="GET">
         {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>
  </nav>

shop/templates/shop/category.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to the cushion store where tou can but confy and awesome chusions
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} - Perfect Cushion Store
    {% else %}
        See Our Collections - Perfect Cushion Store
    {% endif %}
{% endblock %}
{% block content %}
    <!-- Breadcrumb Navigation -->
    {% if category %}
        <div class="row my-row-class">
            <div class="mx-auto">
                <p><a href="{% url 'shop:allProdCat' %}">Our Product Collections</a> | {{ category.name }}</p>
            </div>
        </div>
    {% endif %}
    <div class="mx-auto">
    {% if category %}
        <img class="my-image" src="{{ category.image.url }}" alt="{{ category.name }}">
    </div>
    <br>
    <div>
        <h1 class="text-center my-title">{{ category.name }}</h1>
        <p class="text-justify">{{ category.description }}</p>
    </div>
    {% else %}
    <div>
        <img class="my-image my-image-padding" src="{% static 'img/banner.jpg' %}" alt="Our Products Collections">
    </div>
    <br>
    <div>
        <h1 class="text-center my-title">Our Products Collections</h1>
        <p class="text-justify">
            Finding the perfect cushion for your room can instantly add to the levels of comfort and sense of style throughout your home.
            They can transform the blandest of decors instantly by adding colour, softness and an air of cosiness. As well as being comfy
            and looking great our range of cushions will certainly embolden your decor with persinalized charm.
        </p>
    </div>
    {% endif %}
    <div class="container">
        <div class="row mx-auto">
            {% for product in products.object_list %}
            <div class="my-bottom-margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                <div class="card text-center" style="min-width: 18rem;">
                    <a href="{{ product.get_url }}"><img class="card-img-top my-image" src="{{ product.image.url }}" alt="{{ product.name }}"></a>
                    <div class="card-body">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.price }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                <a href="?page={{ pg }}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{ pg }}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>    
        
{% endblock %}

shop/templates/shop/product.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block metadescription %}
    {{ product.description | truncatewords:155 }}
{% endblock %}
{% block title %}
    {{ product.name}} - Perfect Cushion Store 
{% endblock %}
{% block content %}
    <div class="row my-prod-row-class">
        <div class="mx-auto">
            <p><a href="{% url 'shop:allProdCat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{ product.category }}</a> | {{ product.name }}</p>
        </div>
    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md 12 col-lg-6 text-center">
                <div style="min-width: 18rem;">
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" style="max-width: -webkit-fill-available">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <div>
                    <h1 class="my-prod-title">{{ product.name }}</h1>
                    <p>{{ product.price }}</p>
                    <p class="my-title">Product Description</p>
                    <p class="text-justify my-prod-text">{{ product.description }}</p>
                    {% if product.stock <= 0 %} 
                        <p class="text-justify my-prod-text"><b>Out of Stock</b></p>
                    {% else %}
                        <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}